### ISSUE TITLE
Can't find core directory

### ISSUE THREAD

**Issue by ramsbod** [thingwala/geyserwala-ha#1]
I am using Home assistant with its own operating system.  Using Samba share I can't find the core directory.

**Comment by thingwala** [comment]
In Home Assistant with its own operating system, the core directory is not accessible via Samba share by default. To access the the core directory, you'll have to use alternative methods, such as the File Editor add-on within Home Assistant, or SSH/SCP/etc.

**Comment by ramsbod** [comment]
I tried SSH.  There is no core directory under the homeassistant directory.

**Comment by ramsbod** [comment]
I am running HA on a raspberry PI with HASS OS.  Maybe the file structure is different?

**Comment by thingwala** [comment]
There should still be a config directory.

This is not an issue specific to this integration. Standard documentation for installing a custom integration on your platform should apply. Closing.
