### ISSUE TITLE
Pump and Element seconds sensors

### ISSUE THREAD

**Issue by svisagie** [thingwala/geyserwala-ha#2]
Great product, and this is more of a feature request than a bug:

Can Pump and Element seconds be exposed as sensors on the device in HA? 

Sure, I can go make use of history_stats, but it will never be as accurate as the data from the Geyserwala

**Comment by thingwala** [comment]
Thank you

`pump-seconds` and `element-seconds` are currently available on MQTT and the REST API (https://github.com/thingwala/geyserwala-connect/tree/main/docs). We don't necessarily want to bloat the integration by adding all the available operational values. Perhaps it is possible to add customisable elements to HA, we've added an item to our back log to see what we can do.

**Comment by thingwala** [comment]
@svisagie FYI in v0.0.8 it is now possible to add custom entities, see: https://github.com/thingwala/geyserwala-ha?tab=readme-ov-file#custom-entities

**Comment by svisagie** [comment]
Awesome.. I'll be trying this out soon
