### ISSUE TITLE
Followed guide but device not autodiscovered and not available under ADD Integration

### ISSUE THREAD

**Issue by AlmostGinger** [thingwala/geyserwala-ha#3]
Followed the guide with configuring HACS, using SAMBA to cope the folder structure across under custom_components.

I have;
-Cleared browser cache
-Restarted HA

Issue persists. Any advice?

**Comment by thingwala** [comment]
* ? This is a HA custom integration, unrelated to HACS - we do hope to add it to HACS in the future
* Ensure that `custom_components/` is placed in the `config/` folder. Typically on HA OS `config/` is found at the SAMBA root. Inside `config/` one should see `configuration.yaml` and other YAML files. 
* Ensure that there are no repeated folder levels.
* Drop in using the Terminal and verify path structure is as expected and all files exist.

**Comment by AlmostGinger** [comment]
Thanks, I was away, I'll give the above a whirl and close this when it works.

**Comment by AlmostGinger** [comment]
I was being daft. Took the whole repo to HA instead of the sub-folder like below. Thanks for the guidance and assistance.

![image](https://github.com/user-attachments/assets/42829948-89ac-450d-938c-f1c56bb90cfa)
