### ISSUE TITLE
Timers

### ISSUE THREAD

**Issue by w1tw0lf** [thingwala/geyserwala-ha#4]
Looking for away to update, change timers via home assistant. Is it possible ?

**Comment by thingwala** [comment]
Feel free to propose a pull request to do this.

Alternatively, see https://www.thingwala.com/geyserwala/connect/integration#rest-api and https://www.home-assistant.io/integrations/rest_command/

**Comment by w1tw0lf** [comment]
Thanks for the links.

Will have a look, but no expert on doing "coding" for HA.
